web:
  build: nginx/.
  container_name: nginx
  ports:
    - "80:80"
  links:
    - "openchain"
  restart: always

openchain:
  image: openchain/server:0.4.3
  ports:
    - "8080"
  volumes:
    - ./data:/openchain.server/approot/src/Openchain.Server/Webroot/App_Data
  restart: always
